background_b: 255
background_g: 86
background_r: 500
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_dave__37691: 'http://Dave:37691/'}
rosversion: '1.12.14

  '
run_id: 5d03e9f2-1d29-11e9-840f-485b3939ae4e
